data:
  img_dict: 'data/090303/img_cell_dict_test-1.npy' # Path of npy file 
  imgs: 'data/090303/test' # Path of test images

test:
  save_path: 'data/outputs-pred-1'
  model_path: '/home/hzhang/zhanghaishan/docs/GraphQP/checkpoints/CP_epoch1.pth'
  pp_model_path: '/home/hzhang/zhanghaishan/docs/GraphQP/pp_model/CP_epoch100.pth'
  win_size: [25, 25]

graph_model_params:

  model_input_params:
    edge_init_dim: 18 # Dimension of edge features
    node_init_dim: 2500 # Dimension of node features

  edge_model_feats_dict:
    fc_dims: [1000, 100] 
    dropout_p: 0
    use_batchnorm: False

  node_model_feats_dict:
    fc_dims: [1000, 100] 
    dropout_p: 0
    use_batchnorm: False