# Hydra configuration file for training

dataset_params:
  train:
    g_stc: 'data/090303/debug/g_structure.txt'                     # Path of txt file 'g_structure' constructed by graph_construct.py 
    csv: 'data/090303/debug'

  eval:
    g_stc: 'data/090303/debug/g_structure.txt'                      # None is OK. In that case, eval.rate in the training data is used for evaluation.
    csv: 'data/090303/debug'
    rate: 0.1                    # Evaluation rate for no eval data

output:
  save: True
  dir: 'checkpoints/'

load: False                   # If you use a trained model, please rewrite it.

train_params:
  prob_size: 5                 # Number of nodes for graph cur and nxt
  epochs: 1                   # Number of epoch
  batch_size: 2                 # Batch size
  lr: 0.0001                    # Learning rate of Adam
  weight_loss_n: 1

graph_model_params:

  model_input_params:
    edge_init_dim: 18 # Dimension of edge features
    node_init_dim: 2500 # Dimension of node features

  edge_model_feats_dict:
    fc_dims: [1000, 100] # Dimension of FC layers 
    dropout_p: 0
    use_batchnorm: False

  node_model_feats_dict:
    fc_dims: [1000, 100] 
    dropout_p: 0
    use_batchnorm: False

