dataset_params:
  train:
    gt_tracks: 'data/F009.mat'                      # Path of file 'img_cell_dict.npy' 
    imgs: 'data/F009'

  eval:
    gt_tracks:                       # None is OK. In that case, eval.rate in the training data is used for evaluation.
    imgs: 
    rate: 0.2                   # Evaluation rate for no eval data

  test:
    imgs: '/home/hzhang/zhanghaishan/docs/GraphQP/data/090303/val-2/F0007'

  data:
    img_shape: [1042, 1390]     # Real input image size
    edge: 10                    # Size of cropped edge 
    win_size: [256, 256]        # Size of crop height
    pp_model_path: '/home/hzhang/zhanghaishan/docs/GraphQP/pp_model/CP_model_epoch10.pth'           # Path of model for pre processing

output:
  save: True
  dir: 'checkpoints_pre/'

load: False                   # If you use a trained model, please rewrite it.

train_params:
  prob_size: 10                 # number of nodes for graph cur and nxt
  epochs: 10                   # Number of epoch
  batch_size: 16                 # Batch size
  lr: 0.00001                    # Learning rate of Adam
  weight_loss_n: 1